### ISSUE TITLE
Accessing the filtered data from viewmodel?

### ISSUE THREAD

**Issue by rolst5** [dotnet/DataGridExtensions#47] opened 2020-12-17 20:16 UTC
Have a WPF Page using a MultiSelectDataGrid and its ItemSource is binding to a CollectionViewSource within a viewmodel.  DGX filtering works beautifully, but I'm not sure how I can access/navigate the filtered data -  whether from the ViewModel's CollectionViewSource or directly from XAML CodeBehind.  With filters applied, my CollectionViewSource data always contains the unfiltered list.

Any examples that show how to access the filtered data?

**Comment by tom-englert** [comment] 2020-12-18 05:31
As the name implies, CollectionViewSource is only the source of the CollectionView. The CollectionView has the filtered list.

**Comment by tom-englert** [comment] 2020-12-18 14:20
Duplicate of #46

**Closed by tom-englert** 2020-12-18 14:20 UTC

**Comment by rolst5** [comment] 2020-12-18 16:06
Thank you very much Mr. Englert.  That pointed me in the right direction.  It works well.  Thanks for the push as well as this great extension.
