### ISSUE TITLE
XAML Errors

### ISSUE THREAD

**Issue by sparedevone** [dotnet/DataGridExtensions#74] opened 2021-11-01 20:39 UTC
Recent version of Visual Studio 2019 notify a couple of XAML errors, e.g.:
`XLS0415	The attachable property 'IsFilterVisible' was not found in type 'DataGridFilterColumn'.	DataGridExtensionsSample`

It looks like `IsFilterVisible` attached property used like an extension method:
- `public static bool GetIsFilterVisible(this DataGridColumn column)`
- `public static void SetIsFilterVisible(this DataGridColumn column, bool value)`

Removing `this` statement solved this issue:
- `public static bool GetIsFilterVisible(DataGridColumn column)`
- `public static void SetIsFilterVisible(DataGridColumn column, bool value)`

A couple of attached properties affected at DataGridFilterColumn.cs and DataGridFilter.cs.

**Comment by tom-englert** [comment] 2021-11-02 05:30
Duplicate of #57

**Closed** 2021-11-02 05:30 UTC
Labels: duplicate
